import { createAsyncAction } from "typesafe-actions";

const FEEDBACK_STATISTICS_REQUEST = "FEEDBACK_STATISTICS_REQUEST";
const FEEDBACK_STATISTICS_SUCCESS = "FEEDBACK_STATISTICS_SUCCESS";
const FEEDBACK_STATISTICS_FAIL = "FEEDBACK_STATISTICS_FAIL";

const FEEDBACK_BADGE_REQUEST = "FEEDBACK_BADGE_REQUEST";
const FEEDBACK_BADGE_SUCCESS = "FEEDBACK_BADGE_SUCCESS";
const FEEDBACK_BADGE_FAIL = "FEEDBACK_BADGE_FAIL";

export const feedbackBadgeActionAsync = createAsyncAction(
  FEEDBACK_BADGE_REQUEST,
  FEEDBACK_BADGE_SUCCESS,
  FEEDBACK_BADGE_FAIL
)<any, any, Error>();

export const feedbackBadgeActionTypes = {
  FEEDBACK_BADGE_REQUEST,
  FEEDBACK_BADGE_SUCCESS,
  FEEDBACK_BADGE_FAIL,
};

export const feedbackStatisticsActionAsync = createAsyncAction(
  FEEDBACK_STATISTICS_REQUEST,
  FEEDBACK_STATISTICS_SUCCESS,
  FEEDBACK_STATISTICS_FAIL
)<any, any, Error>();

export const feedbackStatisticsActionTypes = {
  FEEDBACK_STATISTICS_REQUEST,
  FEEDBACK_STATISTICS_SUCCESS,
  FEEDBACK_STATISTICS_FAIL,
};
